CREATE TABLE TITLES (
	TITLE_ID VARCHAR(5) PRIMARY KEY,
    TITLE VARCHAR(30)
);

CREATE TABLE DEPARTMENTS (
	DEPT_NO VARCHAR(5) PRIMARY KEY,
	DEPT_NAME VARCHAR(30)
);

CREATE TABLE EMPLOYEES (
	EMP_NO integer PRIMARY KEY,
	EMP_TITLE_ID VARCHAR(5) NOT NULL,
	BIRTH_DATE date, FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL,
	SEX VARCHAR(1),
	HIRE_DATE date
);

CREATE TABLE SALARIES (
	EMP_NO INTEGER PRIMARY KEY,
	SALARY INTEGER NOT NULL
);

CREATE TABLE DEPARTMENT_EMPLOYEES(
	EMP_NO INTEGER NOT NULL,
    DEPT_NO VARCHAR(5) NOT NULL,
	PRIMARY KEY(EMP_NO,DEPT_NO)
);

CREATE TABLE DEPARTMENT_MANAGER(
	DEPT_NO VARCHAR(5) NOT NULL,
	EMP_NO integer NOT NULL,
	PRIMARY KEY(DEPT_NO, EMP_NO)
);


